#!/usr/bin/env bash

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset
# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail
readonly __DEBUG="${MP_DEBUG:=0}"

# Define field seperator for word spllitting
# IFS=$' \n\t'

# set debug output
if [[ ${__DEBUG} = 1 || ${__DEBUG} = "TRUE" ]]; then
  set -o xtrace #Turn on traces, useful while debugging but unset by default
fi

# constants and environment
declare -xr VAULT_ADDR="http://127.0.0.1:8200"

# local functions

### simple error trap
err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
}

chmod +x "${HOME}"/*.sh
echo "installing vault"
"${HOME}"/01-install_vault_ent.sh
# read -r -t 30 -p "Press any key to resume ..."
curl -s ${VAULT_ADDR}/v1/sys/seal-status | jq '.initialized'
# false
echo "initializing vault"
"${HOME}"/02-run_vault.sh
"${HOME}"/03-config_vault.sh
